name: Create Tagged Release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: version
        run: |
          echo "VERSION=$(ruby ./scripts/print_version.rb ./version.txt)" >> $GITHUB_OUTPUT
      - name: Create release
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          gh release create "v-$VERSION" --generate-notes
      - name: Delete branch
        if: ${{ github.head_ref != 'master' }} # To not delete master ever 😉
        run: |
          git push origin -d $GITHUB_REF # delete the release branch after release is created

