# Automatically raise a PR with the changes merged into release branch to master branch
name: On PR Merged to release branch
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
env:
  BASE_BRANCH: ${{ github.base_ref }} # release branch
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_TITLE: ${{ github.event.pull_request.title }}
  TZ: +05:30 # Required for the Ruby script to pick the right date in version
  GH_TOKEN: ${{ github.token }}

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    secrets: inherit
    uses: ./.github/workflows/update-version.yml
    with:
      branch: ${{ github.base_ref }}
      commit_message: "[Bot] Bump version after #${{ github.event.pull_request.number }}"
      flags: '--only-patch'

  raise-backmerge-pr-using-cherry-pick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Cherry Pick
        env:
          COMMIT_TO_BACKMERGE: ${{ github.sha }}
        run: |
          git switch -c "auto-backmerge/$PR_NUMBER"
          git fetch origin $COMMIT_TO_BACKMERGE
          git -c user.email=praja-ci@praja.buzz -c user.name=praja-ci cherry-pick $COMMIT_TO_BACKMERGE # might fail if conflicts are present
          git push origin HEAD
          gh pr create --title "Backmerge #$PR_NUMBER: $PR_TITLE" --body "Backmerge from $BASE_BRANCH to master" --base master
          gh pr merge --auto --squash

  raise-backmerge-pr-from-base-branch:
    if: ${{ always() && needs.raise-backmerge-pr-using-cherry-pick.result == 'failure' }}
    needs: raise-backmerge-pr-using-cherry-pick
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Create PR from a backmerge branch
        run: |
          git switch -c "auto-backmerge/$PR_NUMBER"
          git push origin HEAD
          gh pr create --title "Backmerge #$PR_NUMBER: $PR_TITLE" --body "Backmerge from $BASE_BRANCH to master" --base master
          gh pr merge --auto --squash
      - name: Checkout to release branch
        run: |
          git switch $BASE_BRANCH
      - name: Run Update Version Script
        run: |
          ruby scripts/update_version.rb ./version.txt --only-patch
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Bump version after #${{ github.event.pull_request.number }}"
          branch: ${{ github.base_ref }}

