name: On PR Merge to master

on:
  pull_request:
    types:
      - closed
    branches:
      - master

env:
  TZ: +05:30 # Required for the Ruby script to pick the right date in version

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    secrets: inherit
    uses: ./.github/workflows/update-version.yml
    with:
      branch: ${{ github.base_ref }}
      commit_message: "[Bot] Bump version after #${{ github.event.pull_request.number }}"
