name: Update version on merge to master

on:
  pull_request:
    types:
      - closed
    branches:
      - master

env:
  TZ: +05:30 # Required for the Ruby script to pick the right date in version

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}

    - name: Run Update Version Script
      run: |
        ruby scripts/update_version.rb ./version.txt

    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Bot] Bump version after #${{ github.event.pull_request.number }}"
        branch: ${{ github.base_ref }}
