# Automatically raise a PR with the changes merged into release branch to master branch
name: On PR Merged to release branch
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
env:
  BASE_BRANCH: ${{ github.base_ref }} # release branch
  PR_NUMBER: ${{ github.event.pull_request.number }}
  TZ: +05:30
  GH_TOKEN: ${{ github.token }}

jobs:
  raise-backmerge-pr-and-bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Create PR from a backmerge branch
        run: |
          git switch -c "auto-backmerge/$PR_NUMBER"
          git push origin HEAD
          gh pr create --title "Backmerge #$PR_NUMBER" --body "Backmerge from release to master" --base master
          gh pr merge --auto --squash

      - name: Checkout to release branch
        run: |
          git switch $BASE_BRANCH

      - name: Run Update Version Script
        run: |
          ruby scripts/update_version.rb ./version.txt --only-patch

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Bump version - #${{ github.event.pull_request.number }}"
          branch: ${{ github.base_ref }}
