name: Update version on master change

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

env:
  TZ: +05:30

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{secrets.AUTOMATION_TOKEN}}

    - name: Run Update Version Script
      run: |
        ruby scripts/update_version.rb ./version.txt

    - name: Commit and push
      run: |
        git add version.txt
        git commit -m "Update Version on master" --author "Gitbot <gitbot@okmanideep.me>"
        git push origin master
